### ISSUE TITLE
bucket4j starter, spring boot 2.7.15, Java 17 error: ClassCastException String cannot be cast to class [B

### ISSUE THREAD

**Issue by www-viveksharma** [MarcGiffing/bucket4j-spring-boot-starter#186]
Using bucket4j starter with spring boot version 2.7.15 and Java 17 (openJdk) along with redis (redisson-spring-boot-starter ver 3.23.2)
getting an error when trying to do : `bucket.tryConsumeAsMuchAsPossible(num);`

Error:
```
javax.cache.processor.EntryProcessorException: java.lang.ClassCastException: class java.lang.String cannot be cast to class [B (java.lang.String and [B are in module java.base of loader 'bootstrap')
    at org.redisson.jcache.JCache.invoke(JCache.java:3067)
    at io.github.bucket4j.grid.jcache.JCacheProxyManager.execute(JCacheProxyManager.java:82)
    at io.github.bucket4j.distributed.proxy.AbstractProxyManager$DefaultRemoteBucketBuilder$1.execute(AbstractProxyManager.java:197)
    at io.github.bucket4j.distributed.proxy.DefaultBucketProxy.execute(DefaultBucketProxy.java:208)
    at io.github.bucket4j.distributed.proxy.DefaultBucketProxy.consumeAsMuchAsPossibleImpl(DefaultBucketProxy.java:78)
    at io.github.bucket4j.AbstractBucket.tryConsumeAsMuchAsPossible(AbstractBucket.java:307)
```
Caused by: 
```
java.lang.ClassCastException: class java.lang.String cannot be cast to class [B (java.lang.String and [B are in module java.base of loader 'bootstrap')
    at io.github.bucket4j.grid.jcache.JCacheProxyManager$JCacheTransaction.getRawState(JCacheProxyManager.java:188)
    at io.github.bucket4j.distributed.remote.AbstractBinaryTransaction.get(AbstractBinaryTransaction.java:72)
    at io.github.bucket4j.distributed.remote.commands.ConsumeAsMuchAsPossibleCommand.execute(ConsumeAsMuchAsPossibleCommand.java:109)
    at io.github.bucket4j.distributed.remote.AbstractBinaryTransaction.execute(AbstractBinaryTransaction.java:53)
    at io.github.bucket4j.grid.jcache.JCacheProxyManager$BucketProcessor.process(JCacheProxyManager.java:167)
    at io.github.bucket4j.grid.jcache.JCacheProxyManager$BucketProcessor.process(JCacheProxyManager.java:155)
    at org.redisson.jcache.JCache.invoke(JCache.java:3055)
```

**Comment by www-viveksharma** [comment]
found that I had the following in my redisson config yaml which I was using:
```
codec: !<org.redisson.codec.JsonJacksonCodec> {}
```
removed this and able to see at least the basic functionality working.
will proceed to testing the clustered redis deployment testing next.
