### ISSUE TITLE
BeanInstantiationException when upgrading to 0.10.2

### ISSUE THREAD

**Issue by 5pielername** [MarcGiffing/bucket4j-spring-boot-starter#222]
Just tried to upgrade from `0.10.1` to `0.10.2` and get the following Exception when Spring Context is starting to run test class:

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.giffing.bucket4j.spring.boot.starter.config.cache.jcache.JCacheCacheListener]: Factory method 'configCacheListener' threw exception with message: Cannot invoke 
"javax.cache.Cache.registerCacheEntryListener(javax.cache.configuration.CacheEntryListenerConfiguration)" because "cache" is null
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:177)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651)
	... 41 more
Caused by: java.lang.NullPointerException: Cannot invoke "javax.cache.Cache.registerCacheEntryListener(javax.cache.configuration.CacheEntryListenerConfiguration)" because "cache" is null
	at com.giffing.bucket4j.spring.boot.starter.config.cache.jcache.JCacheCacheListener.<init>(JCacheCacheListener.java:31)
	at com.giffing.bucket4j.spring.boot.starter.config.cache.jcache.JCacheBucket4jConfiguration.configCacheListener(JCacheBucket4jConfiguration.java:48)
	at com.giffing.bucket4j.spring.boot.starter.config.cache.jcache.JCacheBucket4jConfiguration$$SpringCGLIB$$0.CGLIB$configCacheListener$2(<generated>)
	at com.giffing.bucket4j.spring.boot.starter.config.cache.jcache.JCacheBucket4jConfiguration$$SpringCGLIB$$FastClass$$1.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at com.giffing.bucket4j.spring.boot.starter.config.cache.jcache.JCacheBucket4jConfiguration$$SpringCGLIB$$0.configCacheListener(<generated>)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:140)
```

Current project is using Spring Boot `3.2.1` with EHCache

```
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-cache</artifactId>
        </dependency>
        <dependency>
            <groupId>org.ehcache</groupId>
            <artifactId>ehcache</artifactId>
            <classifier>jakarta</classifier>
        </dependency>
```

```
spring:
  cache:
    jcache:
      config: classpath:ehcache.xml
bucket4j:
  enabled: true
  filters:
    - cache-name: buckets
      url: /api/v1/test.*
      rate-limits:
        - bandwidths:
            - capacity: 3
              time: 5
              unit: minutes
```

and cache configuration 

```
<config xmlns='http://www.ehcache.org/v3'
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:jsr107="http://www.ehcache.org/v3/jsr107"
        xsi:schemaLocation="http://www.ehcache.org/v3 http://www.ehcache.org/schema/ehcache-core-3.0.xsd
							http://www.ehcache.org/v3/jsr107 http://www.ehcache.org/schema/ehcache-107-ext-3.0.xsd">
    <cache alias="buckets">
        <expiry>
            <ttl unit="seconds">3600</ttl>
        </expiry>
        <heap unit="entries">1000000</heap>
        <jsr107:mbeans enable-statistics="true"/>
    </cache>
</config>
```

Test class is configured to use complete context:

```
@SpringBootTest
@AutoConfigureMockMvc
public class DemoApplicationTests {
// ..
```

Main Class is annotated

```
@SpringBootApplication
@EnableCaching
public class DemoApplication {
// ..
```

The same code is working fine with `0.10.1`.

**Comment by Edwin9292** [comment]
First of all, I want to appologize for the inconvenience and thank you for reporting the issue and providing all the information. 
With the provided error message it was easy to discover the problem. It appears there was a mistake that I overlooked while implementing the dynamic updating feature, where config caching is auto-enabled if the 'filter-config-caching-enabled' property is missing. 

I'm testing the fix right now and will create a pull request for @MarcGiffing as soon as I'm done.

In the meanwhile you should be able to fix the issue by setting the following property in your application.yml:
``` 
bucket4j:
  filter-config-caching-enabled: false
```
or `bucket4j.filter-config-caching-enabled=false` if you use application.properties. 

As an alternative you cold look at the documentation in the readme about enabling dynamically updating rate limits. If you add a cache called 'filterConfigCache' (or use a different name by setting the 'filter-config-cache-name' property) and set the other required properties as specified in the documentation, the issue should also be resolved.
