### ISSUE TITLE
Cannot invoke Bucket4JBootProperties.getMethods()" because "bucket4jProperties" is null

### ISSUE THREAD

**Issue by roma2341** [MarcGiffing/bucket4j-spring-boot-starter#297]
I have an error:
```
2024-05-02T17:38:15.031+03:00  WARN 165391 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [com.giffing.bucket4j.spring.boot.starter.config.cache.Bucket4jCacheConfiguration]: Error processing condition on com.giffing.bucket4j.spring.boot.starter.config.cache.jcache.JCacheBucket4jConfiguration
2024-05-02T17:38:15.037+03:00  INFO 165391 --- [           main] .s.b.a.l.ConditionEvaluationReportLogger : 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-05-02T17:38:15.057+03:00 ERROR 165391 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [com.giffing.bucket4j.spring.boot.starter.config.cache.Bucket4jCacheConfiguration]: Error processing condition on com.giffing.bucket4j.spring.boot.starter.config.cache.jcache.JCacheBucket4jConfiguration
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:544) ~[spring-context-6.1.3.jar:6.1.3]
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:321) ~[spring-context-6.1.3.jar:6.1.3]
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:246) ~[spring-context-6.1.3.jar:6.1.3]
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:534) ~[spring-context-6.1.3.jar:6.1.3]
	at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGroupingHandler.lambda$processGroupImports$1(ConfigurationClassParser.java:746) ~[spring-context-6.1.3.jar:6.1.3]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGroupingHandler.processGroupImports(ConfigurationClassParser.java:743) ~[spring-context-6.1.3.jar:6.1.3]
	at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorHandler.process(ConfigurationClassParser.java:714) ~[spring-context-6.1.3.jar:6.1.3]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:183) ~[spring-context-6.1.3.jar:6.1.3]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:416) ~[spring-context-6.1.3.jar:6.1.3]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:289) ~[spring-context-6.1.3.jar:6.1.3]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:349) ~[spring-context-6.1.3.jar:6.1.3]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:118) ~[spring-context-6.1.3.jar:6.1.3]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:788) ~[spring-context-6.1.3.jar:6.1.3]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:606) ~[spring-context-6.1.3.jar:6.1.3]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.2.2.jar:3.2.2]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-3.2.2.jar:3.2.2]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[spring-boot-3.2.2.jar:3.2.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:334) ~[spring-boot-3.2.2.jar:3.2.2]
	at com.shs.CrmApplication.main(CrmApplication.java:20) ~[classes/:na]
Caused by: java.lang.IllegalStateException: Error processing condition on com.giffing.bucket4j.spring.boot.starter.config.cache.jcache.JCacheBucket4jConfiguration
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:60) ~[spring-boot-autoconfigure-3.2.2.jar:3.2.2]
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:108) ~[spring-context-6.1.3.jar:6.1.3]
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:220) ~[spring-context-6.1.3.jar:6.1.3]
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:534) ~[spring-context-6.1.3.jar:6.1.3]
	... 19 common frames omitted
Caused by: java.lang.NullPointerException: Cannot invoke "com.giffing.bucket4j.spring.boot.starter.context.properties.Bucket4JBootProperties.getMethods()" because "bucket4jProperties" is null
	at com.giffing.bucket4j.spring.boot.starter.config.condition.OnSynchronousPropertyCondition.getMatchOutcome(OnSynchronousPropertyCondition.java:15) ~[bucket4j-spring-boot-starter-0.12.6.jar:0.12.6]
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47) ~[spring-boot-autoconfigure-3.2.2.jar:3.2.2]
	... 22 common frames omitted

```

**Comment by roma2341** [comment]
Error was unclear, fixed by adding these lines to application.yaml:
```
bucket4j:
  enabled: true
  
```

**Comment by MarcGiffing** [comment]
I coudn't find the root cause but I hope the MR will fix the exception

**Comment by ShriramDeshkar** [comment]
Getting the same error 
NullPointerException: Cannot invoke com.giffing.bucket4j.spring.boot.starter.context.properties.Bucket4JBootProperties.getMethods() because bucket4jProperties is null
I m getting this error from version 0.12.3 onwards

**Comment by roma2341** [comment]
> @MarcGiffing Getting the same error please find below error description I m getting.
> 
> NullPointerException: Cannot invoke com.giffing.bucket4j.spring.boot.starter.context.properties.Bucket4JBootProperties.getMethods() because bucket4jProperties is null. I m getting this error from version 0.12.3 onwards.

Did you try "bucket4j.enabled=true" option in application properties?
