### ISSUE TITLE
redis-lettuce example broken

### ISSUE THREAD

**Issue by mf-guse** [MarcGiffing/bucket4j-spring-boot-starter#343]
Unfortunately I have some trouble getting bucket4j-spering-boot-starter running with Lettuce. Therefore I wanted to try how bucket4j-spring-boot-starter behaves with the examples.

I checked out https://github.com/MarcGiffing/bucket4j-spring-boot-starter.git into IntelliJ, configured a JDK 17 into my Windows 11 machine. IntelliJ uses the bundled Maven v 3.9.8.

Starting the RedisLettuceApplication from IntelliJ (right clickt -> Run) fails with 

```
Caused by: java.lang.IllegalStateException: Failed to introspect Class [com.giffing.bucket4j.spring.boot.starter.config.aspect.RateLimitAspect] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@1d44bcfa]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:483) ~[spring-core-6.1.8.jar:6.1.8]
	at org.springframework.util.ReflectionUtils.doWithLocalMethods(ReflectionUtils.java:320) ~[spring-core-6.1.8.jar:6.1.8]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.checkLookupMethods(AutowiredAnnotationBeanPostProcessor.java:475) ~[spring-beans-6.1.8.jar:6.1.8]
	... 19 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/aspectj/lang/ProceedingJoinPoint
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[na:na]
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[na:na]
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504) ~[na:na]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:465) ~[spring-core-6.1.8.jar:6.1.8]
	... 21 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.aspectj.lang.ProceedingJoinPoint
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
	... 25 common frames omitted
```

After adding the dependency 

```
 <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-aop</artifactId>
  </dependency>
```
to the redis-lettuce example pom the start fails with

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 2 of constructor in com.giffing.bucket4j.spring.boot.starter.config.aspect.RateLimitAspect required a bean of type 'com.giffing.bucket4j.spring.boot.starter.config.cache.SyncCacheResolver' that could not be found.


Action:

Consider defining a bean of type 'com.giffing.bucket4j.spring.boot.starter.config.cache.SyncCacheResolver' in your configuration.
```

which is similar to the fact in my application that no CacheResolver is found. It seems the Autoconfiguration for the Redis stuff is not working properly.

It would be nice if you could repair the redis-lettuce example or give any hint how to configure the method annotation `@RateLimiting` correctly to work with redis.

Thank you in advance!

**Comment by MarcGiffing** [comment]
You're right. The com.giffing.bucket4j.spring.boot.starter.config.aspect.RateLimitAspect is falsely annotated with @Component. The class is configured in Bucket4jAopConfig only if the Aspect class is present.
![image](https://github.com/user-attachments/assets/0c5b5dfd-393c-4979-a9f6-051acfa20689)

**Comment by MarcGiffing** [comment]
@mf-guse I've provided a merge request:
https://github.com/MarcGiffing/bucket4j-spring-boot-starter/pull/345
