### ISSUE TITLE
Caused by: java.lang.NullPointerException: Cannot invoke "javax.cache.Cache.get(Object)" because "this.cache" is null

### ISSUE THREAD

**Issue by gangadharkasturi** [MarcGiffing/bucket4j-spring-boot-starter#357]
Need to connect to exisitng hazelcast member using hazelcast-client.xml , used the given example and changed the configs to below.
```

spring:
  cache:
    type: jcache
    jcache:
      provider: com.hazelcast.client.cache.impl.HazelcastClientCachingProvider
      config: hazelcast-client.xml
```

**hazelcast-client.xml:**

```
<hazelcast-client xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://www.hazelcast.com/schema/client-config
                               http://www.hazelcast.com/schema/client-config/hazelcast-client-config-5.5.xsd"
                  xmlns="http://www.hazelcast.com/schema/client-config">

    <cluster-name>dev</cluster-name>

    <network>
        <cluster-members>
            <address>127.0.0.1:5701</address>
        </cluster-members>
    </network>
</hazelcast-client>
```
Using JDK 17 and boot 3.1.2.

**POM.XML**

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.1.2</version>
		<relativePath /> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.oardic</groupId>
	<artifactId>springboot-bucket4j-example</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>springboot-bucket4j-example</name>
	<description>Demo project for Spring Boot</description>
	<properties>
		<java.version>17</java.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-cache</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-validation</artifactId>
		</dependency>
		<dependency>
			<groupId>com.giffing.bucket4j.spring.boot.starter</groupId>
			<artifactId>bucket4j-spring-boot-starter</artifactId>
			<version>0.10.3</version>
		</dependency>
		<dependency>
			<groupId>javax.cache</groupId>
			<artifactId>cache-api</artifactId>
		</dependency>
		<dependency>
			<groupId>com.hazelcast</groupId>
			<artifactId>hazelcast</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
	</dependencies>

</project>

```

It is giving the exception:
```
2024-11-04T17:27:02.139+05:30  INFO 13364 --- [           main] c.o.s.HazelcastApplication               : Starting HazelcastApplication using Java 17.0.8 with PID 13364 (E:\workspaces\RnD\APIGateway-2\springboot-bucket4j-example-jdk17-3\target\classes started by gangadhar.kasturi in E:\workspaces\RnD\APIGateway-2\springboot-bucket4j-example-jdk17-3)
2024-11-04T17:27:02.143+05:30  INFO 13364 --- [           main] c.o.s.HazelcastApplication               : No active profile set, falling back to 1 default profile: "default"
2024-11-04T17:27:03.493+05:30  INFO 13364 --- [           main] c.h.i.config.AbstractConfigLocator       : Loading 'hazelcast-client.xml' from the classpath.
2024-11-04T17:27:03.566+05:30  WARN 13364 --- [           main] c.h.config.AbstractXmlConfigHelper       : Name of the hazelcast schema location[http://www.hazelcast.com/schema/client-config/hazelcast-client-config-5.5.xsd] is incorrect, using default
2024-11-04T17:27:03.947+05:30  INFO 13364 --- [           main] c.h.c.impl.spi.ClientInvocationService   : hz.client_1 [dev] [5.2.4] Running with 2 response threads, dynamic=true
2024-11-04T17:27:04.015+05:30  INFO 13364 --- [           main] com.hazelcast.core.LifecycleService      : hz.client_1 [dev] [5.2.4] HazelcastClient 5.2.4 (20230613 - bcacb08) is STARTING
2024-11-04T17:27:04.016+05:30  INFO 13364 --- [           main] com.hazelcast.core.LifecycleService      : hz.client_1 [dev] [5.2.4] HazelcastClient 5.2.4 (20230613 - bcacb08) is STARTED
2024-11-04T17:27:05.078+05:30  INFO 13364 --- [           main] c.h.c.i.c.ClientConnectionManager        : hz.client_1 [dev] [5.2.4] Trying to connect to cluster: dev
2024-11-04T17:27:05.083+05:30  INFO 13364 --- [           main] c.h.c.i.c.ClientConnectionManager        : hz.client_1 [dev] [5.2.4] Trying to connect to [127.0.0.1]:5701
2024-11-04T17:27:06.110+05:30  INFO 13364 --- [           main] com.hazelcast.core.LifecycleService      : hz.client_1 [dev] [5.2.4] HazelcastClient 5.2.4 (20230613 - bcacb08) is CLIENT_CONNECTED
2024-11-04T17:27:06.110+05:30  INFO 13364 --- [           main] c.h.c.i.c.ClientConnectionManager        : hz.client_1 [dev] [5.2.4] Authenticated with server [192.168.1.219]:5701:6ea54df0-6e3f-45bd-bd2d-3b674bcc3e99, server version: 5.3.1, local address: /127.0.0.1:53480
2024-11-04T17:27:06.112+05:30  INFO 13364 --- [           main] c.h.internal.diagnostics.Diagnostics     : hz.client_1 [dev] [5.2.4] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
2024-11-04T17:27:07.127+05:30  INFO 13364 --- [lient_1.event-5] c.h.c.impl.spi.ClientClusterService      : hz.client_1 [dev] [5.2.4] 

Members [1] {
	Member [192.168.1.219]:5701 - 6ea54df0-6e3f-45bd-bd2d-3b674bcc3e99
}

2024-11-04T17:27:07.173+05:30  INFO 13364 --- [           main] c.h.c.i.s.ClientStatisticsService        : Client statistics is enabled with period 5 seconds.
2024-11-04T17:27:07.219+05:30  WARN 13364 --- [           main] c.h.config.AbstractXmlConfigHelper       : Name of the hazelcast schema location[http://www.hazelcast.com/schema/client-config/hazelcast-client-config-5.5.xsd] is incorrect, using default
2024-11-04T17:27:07.256+05:30  INFO 13364 --- [           main] c.h.c.impl.spi.ClientInvocationService   : file:/E:/workspaces/RnD/APIGateway-2/springboot-bucket4j-example-jdk17-3/target/classes/hazelcast-client.xml [dev] [5.2.4] Running with 2 response threads, dynamic=true
2024-11-04T17:27:07.259+05:30  INFO 13364 --- [           main] com.hazelcast.core.LifecycleService      : file:/E:/workspaces/RnD/APIGateway-2/springboot-bucket4j-example-jdk17-3/target/classes/hazelcast-client.xml [dev] [5.2.4] HazelcastClient 5.2.4 (20230613 - bcacb08) is STARTING
2024-11-04T17:27:07.260+05:30  INFO 13364 --- [           main] com.hazelcast.core.LifecycleService      : file:/E:/workspaces/RnD/APIGateway-2/springboot-bucket4j-example-jdk17-3/target/classes/hazelcast-client.xml [dev] [5.2.4] HazelcastClient 5.2.4 (20230613 - bcacb08) is STARTED
2024-11-04T17:27:07.268+05:30  INFO 13364 --- [           main] c.h.c.i.c.ClientConnectionManager        : file:/E:/workspaces/RnD/APIGateway-2/springboot-bucket4j-example-jdk17-3/target/classes/hazelcast-client.xml [dev] [5.2.4] Trying to connect to cluster: dev
2024-11-04T17:27:07.268+05:30  INFO 13364 --- [           main] c.h.c.i.c.ClientConnectionManager        : file:/E:/workspaces/RnD/APIGateway-2/springboot-bucket4j-example-jdk17-3/target/classes/hazelcast-client.xml [dev] [5.2.4] Trying to connect to [127.0.0.1]:5701
2024-11-04T17:27:07.271+05:30  INFO 13364 --- [           main] com.hazelcast.core.LifecycleService      : file:/E:/workspaces/RnD/APIGateway-2/springboot-bucket4j-example-jdk17-3/target/classes/hazelcast-client.xml [dev] [5.2.4] HazelcastClient 5.2.4 (20230613 - bcacb08) is CLIENT_CONNECTED
2024-11-04T17:27:07.271+05:30  INFO 13364 --- [           main] c.h.c.i.c.ClientConnectionManager        : file:/E:/workspaces/RnD/APIGateway-2/springboot-bucket4j-example-jdk17-3/target/classes/hazelcast-client.xml [dev] [5.2.4] Authenticated with server [192.168.1.219]:5701:6ea54df0-6e3f-45bd-bd2d-3b674bcc3e99, server version: 5.3.1, local address: /127.0.0.1:53482
2024-11-04T17:27:07.272+05:30  INFO 13364 --- [           main] c.h.internal.diagnostics.Diagnostics     : file:/E:/workspaces/RnD/APIGateway-2/springboot-bucket4j-example-jdk17-3/target/classes/hazelcast-client.xml [dev] [5.2.4] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
2024-11-04T17:27:07.274+05:30  INFO 13364 --- [ent.xml.event-8] c.h.c.impl.spi.ClientClusterService      : file:/E:/workspaces/RnD/APIGateway-2/springboot-bucket4j-example-jdk17-3/target/classes/hazelcast-client.xml [dev] [5.2.4] 

Members [1] {
	Member [192.168.1.219]:5701 - 6ea54df0-6e3f-45bd-bd2d-3b674bcc3e99
}

2024-11-04T17:27:07.280+05:30  INFO 13364 --- [           main] c.h.c.i.s.ClientStatisticsService        : Client statistics is enabled with period 5 seconds.
2024-11-04T17:27:07.426+05:30  WARN 13364 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server
2024-11-04T17:27:07.427+05:30  INFO 13364 --- [           main] com.hazelcast.core.LifecycleService      : file:/E:/workspaces/RnD/APIGateway-2/springboot-bucket4j-example-jdk17-3/target/classes/hazelcast-client.xml [dev] [5.2.4] HazelcastClient 5.2.4 (20230613 - bcacb08) is SHUTTING_DOWN
2024-11-04T17:27:07.436+05:30  INFO 13364 --- [           main] c.h.c.i.c.ClientConnectionManager        : file:/E:/workspaces/RnD/APIGateway-2/springboot-bucket4j-example-jdk17-3/target/classes/hazelcast-client.xml [dev] [5.2.4] Removed connection to endpoint: [192.168.1.219]:5701:6ea54df0-6e3f-45bd-bd2d-3b674bcc3e99, connection: ClientConnection{alive=false, connectionId=1, channel=NioChannel{/127.0.0.1:53482->/127.0.0.1:5701}, remoteAddress=[192.168.1.219]:5701, lastReadTime=2024-11-04 17:27:07.317, lastWriteTime=2024-11-04 17:27:07.316, closedTime=2024-11-04 17:27:07.427, connected server version=null}
2024-11-04T17:27:07.436+05:30  INFO 13364 --- [           main] com.hazelcast.core.LifecycleService      : file:/E:/workspaces/RnD/APIGateway-2/springboot-bucket4j-example-jdk17-3/target/classes/hazelcast-client.xml [dev] [5.2.4] HazelcastClient 5.2.4 (20230613 - bcacb08) is CLIENT_DISCONNECTED
2024-11-04T17:27:07.649+05:30  INFO 13364 --- [           main] com.hazelcast.core.LifecycleService      : file:/E:/workspaces/RnD/APIGateway-2/springboot-bucket4j-example-jdk17-3/target/classes/hazelcast-client.xml [dev] [5.2.4] HazelcastClient 5.2.4 (20230613 - bcacb08) is SHUTDOWN
2024-11-04T17:27:07.650+05:30  INFO 13364 --- [           main] com.hazelcast.core.LifecycleService      : hz.client_1 [dev] [5.2.4] HazelcastClient 5.2.4 (20230613 - bcacb08) is SHUTTING_DOWN
2024-11-04T17:27:07.653+05:30  INFO 13364 --- [           main] c.h.c.i.c.ClientConnectionManager        : hz.client_1 [dev] [5.2.4] Removed connection to endpoint: [192.168.1.219]:5701:6ea54df0-6e3f-45bd-bd2d-3b674bcc3e99, connection: ClientConnection{alive=false, connectionId=1, channel=NioChannel{/127.0.0.1:53480->/127.0.0.1:5701}, remoteAddress=[192.168.1.219]:5701, lastReadTime=2024-11-04 17:27:07.166, lastWriteTime=2024-11-04 17:27:07.165, closedTime=2024-11-04 17:27:07.651, connected server version=null}
2024-11-04T17:27:07.653+05:30  INFO 13364 --- [           main] com.hazelcast.core.LifecycleService      : hz.client_1 [dev] [5.2.4] HazelcastClient 5.2.4 (20230613 - bcacb08) is CLIENT_DISCONNECTED
2024-11-04T17:27:07.657+05:30  INFO 13364 --- [           main] com.hazelcast.core.LifecycleService      : hz.client_1 [dev] [5.2.4] HazelcastClient 5.2.4 (20230613 - bcacb08) is SHUTDOWN
2024-11-04T17:27:07.684+05:30  INFO 13364 --- [           main] .s.b.a.l.ConditionEvaluationReportLogger : 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-11-04T17:27:07.710+05:30 ERROR 13364 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Unable to start web server
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:164) ~[spring-boot-3.1.2.jar:3.1.2]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:602) ~[spring-context-6.0.11.jar:6.0.11]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.1.2.jar:3.1.2]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[spring-boot-3.1.2.jar:3.1.2]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:436) ~[spring-boot-3.1.2.jar:3.1.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) ~[spring-boot-3.1.2.jar:3.1.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-3.1.2.jar:3.1.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-3.1.2.jar:3.1.2]
	at com.oardic.springbootbucket4j.HazelcastApplication.main(HazelcastApplication.java:17) ~[classes/:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tomcatServletWebServerFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/ServletWebServerFactoryConfiguration$EmbeddedTomcat.class]: Cannot invoke "javax.cache.Cache.get(Object)" because "this.cache" is null
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:605) ~[spring-beans-6.0.11.jar:6.0.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[spring-beans-6.0.11.jar:6.0.11]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.0.11.jar:6.0.11]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.11.jar:6.0.11]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.0.11.jar:6.0.11]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:205) ~[spring-beans-6.0.11.jar:6.0.11]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.getWebServerFactory(ServletWebServerApplicationContext.java:218) ~[spring-boot-3.1.2.jar:3.1.2]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:181) ~[spring-boot-3.1.2.jar:3.1.2]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:161) ~[spring-boot-3.1.2.jar:3.1.2]
	... 8 common frames omitted
Caused by: java.lang.NullPointerException: Cannot invoke "javax.cache.Cache.get(Object)" because "this.cache" is null
	at com.giffing.bucket4j.spring.boot.starter.config.cache.jcache.JCacheCacheManager.getValue(JCacheCacheManager.java:17) ~[bucket4j-spring-boot-starter-0.10.3.jar:0.10.3]
	at com.giffing.bucket4j.spring.boot.starter.config.filter.Bucket4JBaseConfiguration.getOrUpdateConfigurationFromCache(Bucket4JBaseConfiguration.java:315) ~[bucket4j-spring-boot-starter-0.10.3.jar:0.10.3]
	at com.giffing.bucket4j.spring.boot.starter.config.filter.servlet.Bucket4JAutoConfigurationServletFilter.lambda$customize$1(Bucket4JAutoConfigurationServletFilter.java:109) ~[bucket4j-spring-boot-starter-0.10.3.jar:0.10.3]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[na:na]
	at com.giffing.bucket4j.spring.boot.starter.config.filter.servlet.Bucket4JAutoConfigurationServletFilter.customize(Bucket4JAutoConfigurationServletFilter.java:110) ~[bucket4j-spring-boot-starter-0.10.3.jar:0.10.3]
	at com.giffing.bucket4j.spring.boot.starter.config.filter.servlet.Bucket4JAutoConfigurationServletFilter.customize(Bucket4JAutoConfigurationServletFilter.java:52) ~[bucket4j-spring-boot-starter-0.10.3.jar:0.10.3]
	at com.giffing.bucket4j.spring.boot.starter.config.filter.servlet.Bucket4JAutoConfigurationServletFilter$$SpringCGLIB$$0.customize(<generated>) ~[bucket4j-spring-boot-starter-0.10.3.jar:0.10.3]
	at org.springframework.boot.web.server.WebServerFactoryCustomizerBeanPostProcessor.lambda$postProcessBeforeInitialization$0(WebServerFactoryCustomizerBeanPostProcessor.java:72) ~[spring-boot-3.1.2.jar:3.1.2]
	at org.springframework.boot.util.LambdaSafe$Callbacks.lambda$invoke$0(LambdaSafe.java:287) ~[spring-boot-3.1.2.jar:3.1.2]
	at org.springframework.boot.util.LambdaSafe$LambdaSafeCallback.invoke(LambdaSafe.java:159) ~[spring-boot-3.1.2.jar:3.1.2]
	at org.springframework.boot.util.LambdaSafe$Callbacks.lambda$invoke$1(LambdaSafe.java:286) ~[spring-boot-3.1.2.jar:3.1.2]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092) ~[na:na]
	at org.springframework.boot.util.LambdaSafe$Callbacks.invoke(LambdaSafe.java:286) ~[spring-boot-3.1.2.jar:3.1.2]
	at org.springframework.boot.web.server.WebServerFactoryCustomizerBeanPostProcessor.postProcessBeforeInitialization(WebServerFactoryCustomizerBeanPostProcessor.java:72) ~[spring-boot-3.1.2.jar:3.1.2]
	at org.springframework.boot.web.server.WebServerFactoryCustomizerBeanPostProcessor.postProcessBeforeInitialization(WebServerFactoryCustomizerBeanPostProcessor.java:58) ~[spring-boot-3.1.2.jar:3.1.2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:419) ~[spring-beans-6.0.11.jar:6.0.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1762) ~[spring-beans-6.0.11.jar:6.0.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:598) ~[spring-beans-6.0.11.jar:6.0.11]
	... 16 common frames omitted
```

**Comment by MarcGiffing** [comment]
Please use the latest version [0.12.7](https://github.com/MarcGiffing/bucket4j-spring-boot-starter/releases/tag/bucket4j-spring-boot-starter-parent-0.12.7) and try it again. I can't see any rate limit configuration.

**Comment by gangadharkasturi** [comment]
resolved with latest version
