### ISSUE TITLE
IP based filter does not work with Spring Webflux

### ISSUE THREAD

**Issue by nikos** [MarcGiffing/bucket4j-spring-boot-starter#53]
When making use of spring-webflux

```
   <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-webflux</artifactId>
      <version>2.1.7.RELEASE</version>
    </dependency>
    <dependency>
      <groupId>com.giffing.bucket4j.spring.boot.starter</groupId>
      <artifactId>bucket4j-spring-boot-starter</artifactId>
      <version>0.1.15</version>
    </dependency>
```

and using the config in application.yml

```
bucket4j:
  enabled: true
  filters:
    - cache-name: buckets
      filter-method: webflux
      url: /mgmt/.*
      rate-limits:
        - filter-key-type: IP
          bandwidths:
            - capacity: 5
              time: 10
              unit: seconds
```
calling will lead to:

```
java.lang.IllegalStateException: Unsupported request type class org.springframework.http.server.reactive.ReactorServerHttpRequest
	at com.giffing.bucket4j.spring.boot.starter.config.Bucket4JBaseConfiguration.lambda$getKeyFilter$3(Bucket4JBaseConfiguration.java:188)
	at com.giffing.bucket4j.spring.boot.starter.config.Bucket4JBaseConfiguration.lambda$null$0(Bucket4JBaseConfiguration.java:98)
	at com.giffing.bucket4j.spring.boot.starter.webflux.WebfluxWebFilter.filter(WebfluxWebFilter.java:39)
	at org.springframework.web.server.handler.DefaultWebFilterChain.lambda$filter$0(DefaultWebFilterChain.java:121)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
	at reactor.core.publisher.MonoPeekTerminal.subscribe(MonoPeekTerminal.java:61)
	at reactor.core.publisher.MonoPeekFuseable.subscribe(MonoPeekFuseable.java:74)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
```

**Comment by MarcGiffing** [comment]
I can't reproduce your problem. Can you create an example project. Did you change the Bucket4JBaseConfiguration? There is only a comment on line 188.
